version: '3.8'

services:

  migrate:
    image: migrate/migrate
    networks:
      - cv
    volumes:
      - ./user-service/migrations:/migrations
    command: [ "-path", "/migrations", "-database",  "postgres://postgres:root@postgres:5432/resume?sslmode=disable", "up" ]
    depends_on:
      - postgres-db

  minio:
    image: docker.io/bitnami/minio:2024
    ports:
      - '9000:9000'
      - '9001:9001'
    networks:
      - cv
    volumes:
      - 'minio_data:/data'
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
      - MINIO_DEFAULT_BUCKETS=resumes

  postgres-db:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      PGDATA: /data/postgres
      POSTGRES_DB: resume
    volumes:
      - db:/databasedatadb/postgres
    ports:
      - "5332:5332"
    networks:
      - cv
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d postgres"]
      interval: 30s
      timeout: 10s
      retries: 5

  redis-db:
    container_name: redis-db
    image: redis
    ports:
      - "6380:6380"
    restart: unless-stopped
    networks:
      - cv

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5673:5672"
      - "15673:15672"
    networks:
      - cv
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "check_port_connectivity"]
      interval: 10s
      timeout: 5s
      retries: 5

  user-service:
    container_name: user-service
    build: ./user-service
    depends_on:
      - redis-db
      - postgres-db
    ports:
      - "9090:9090"
    networks:
      - cv

  resume-service:
    container_name: resume-service
    build: ./resume-service
    depends_on:
      - redis-db
      - postgres-db
      - user-service
    ports:
      - "9080:9080"
    networks:
      - cv

  api-service:
    container_name: api-service
    build: ./api-service
    depends_on:
      - redis-db
      - postgres-db
      - resume-service
      - user-service
      - rabbitmq
    environment:
      - AMQP_SERVER=amqp://guest:guest@rabbitmq:5672/
      - QUEUE_NAME=cvmaker_queue
    ports:
      - "8080:8080"
    networks:
      - cv

  consumer:
    build:
      context: ./bot-service
      dockerfile: Dockerfile
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USER=guest
      - RABBITMQ_PASS=guest
      - TELEGRAM_BOT_TOKEN=7303220559:AAHgpp6y1f_dk-iLsZ_gGrjwoI5-9mTVrPY
      - TELEGRAM_CHAT_ID=-1002142909351
      - QUEUE_NAME=cvmaker_queue
    networks:
      - cv

networks:
  cv:
    driver: bridge

volumes:
  db:
  minio_data:
    driver: local
