version: '3.8'

services:

  migrate:
    image: migrate/migrate
    networks:
      - cv
    volumes:
      - ./user-service/migrations:/migrations
    command: [ "-path", "/migrations", "-database",  "postgres://postgres:root@cvmaker_postgres:5432/resume?sslmode=disable", "up" ]
    depends_on:
      postgres-db:
        condition: service_healthy


  minio:
    image: docker.io/bitnami/minio:2024
    ports:
      - '9000:9000'
      - '9001:9001'
    networks:
      - cv
    volumes:
      - 'minio_data:/data'
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
      - MINIO_DEFAULT_BUCKETS=resumes
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9000/minio/health/live || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5

  postgres-db:
    container_name: cvmaker_postgres
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      PGDATA: /data/postgres
      POSTGRES_DB: resume
    volumes:
      - db:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - cv
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d postgres"]
      interval: 30s
      timeout: 10s
      retries: 5

  redis-db:
    container_name: cvmaker_redis-db
    image: redis
    ports:
      - "6380:6380"
    restart: unless-stopped
    networks:
      - cv

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5673:5672"
      - "15673:15672"
    networks:
      - cv
    volumes:
    - rabbitmq_data:/var/lib/rabbitmq
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 40s

  user-service:
    container_name: cvmaker_user-service
    build: ./user-service
    depends_on:
      postgres-db:
        condition: service_healthy
    ports:
      - "9090:9090"
    networks:
      - cv


  resume-service:
    container_name: cvmaker_resume-service
    build: ./resume-service
    depends_on:
      postgres-db:
        condition: service_healthy
      user-service:
        condition: service_started
    ports:
      - "9080:9080"
    networks:
      - cv

  api-service:
    container_name: cvmaker_api-service
    build: ./api-service
    depends_on:
      redis-db:
        condition: service_started
      postgres-db:
        condition: service_started
      resume-service:
        condition: service_started
      user-service:
        condition: service_started
      rabbitmq:
        condition: service_healthy
    environment:
      - AMQP_SERVER=amqp://guest:guest@rabbitmq:5672/
      - QUEUE_NAME=cvmaker_queue
    ports:
      - "9070:9070"
    networks:
      - cv

  consumer:
    build:
      context: ./bot-service
      dockerfile: Dockerfile
    environment:
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USER=guest
      - RABBITMQ_PASS=guest
      - TELEGRAM_BOT_TOKEN=7303220559:AAHgpp6y1f_dk-iLsZ_gGrjwoI5-9mTVrPY
      - TELEGRAM_CHAT_ID=-1002142909351
      - QUEUE_NAME=cvmaker_queue
    depends_on:
      postgres-db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    networks:
      - cv

networks:
  cv:
    driver: bridge

volumes:
  db:
    driver: local
  minio_data:
    driver: local
  rabbitmq_data:
    driver: local
