// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: resume.proto

package resume_service

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

func init() { proto.RegisterFile("resume.proto", fileDescriptor_f12e764066ca2912) }

var fileDescriptor_f12e764066ca2912 = []byte{
	// 90 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x29, 0x4a, 0x2d, 0x2e,
	0xcd, 0x4d, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x37, 0xe2, 0xe7, 0xe2, 0x0d, 0x02, 0xf3, 0x83,
	0x53, 0x8b, 0xca, 0x32, 0x93, 0x53, 0x9d, 0x34, 0x4f, 0x3c, 0x92, 0x63, 0xbc, 0xf0, 0x48, 0x8e,
	0xf1, 0xc1, 0x23, 0x39, 0xc6, 0x19, 0x8f, 0xe5, 0x18, 0xa2, 0xc4, 0xd3, 0x53, 0xf3, 0xc0, 0x8a,
	0xf5, 0x21, 0x3a, 0xe3, 0x8b, 0x21, 0x4a, 0x93, 0xd8, 0xc0, 0xa2, 0xc6, 0x80, 0x00, 0x00, 0x00,
	0xff, 0xff, 0x5b, 0x9c, 0x77, 0x27, 0x52, 0x00, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ResumeServiceClient is the client API for ResumeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ResumeServiceClient interface {
}

type resumeServiceClient struct {
	cc *grpc.ClientConn
}

func NewResumeServiceClient(cc *grpc.ClientConn) ResumeServiceClient {
	return &resumeServiceClient{cc}
}

// ResumeServiceServer is the server API for ResumeService service.
type ResumeServiceServer interface {
}

// UnimplementedResumeServiceServer can be embedded to have forward compatible implementations.
type UnimplementedResumeServiceServer struct {
}

func RegisterResumeServiceServer(s *grpc.Server, srv ResumeServiceServer) {
	s.RegisterService(&_ResumeService_serviceDesc, srv)
}

var _ResumeService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "ResumeService",
	HandlerType: (*ResumeServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams:     []grpc.StreamDesc{},
	Metadata:    "resume.proto",
}
