// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: resume_service.proto

package resume_service

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

func init() { proto.RegisterFile("resume_service.proto", fileDescriptor_b6f3d3ddd1d37e28) }

var fileDescriptor_b6f3d3ddd1d37e28 = []byte{
	// 122 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x29, 0x4a, 0x2d, 0x2e,
	0xcd, 0x4d, 0x8d, 0x2f, 0x4e, 0x2d, 0x2a, 0xcb, 0x4c, 0x4e, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9,
	0x17, 0xe2, 0x43, 0x15, 0x95, 0x12, 0x82, 0xf2, 0x73, 0xf3, 0x53, 0x52, 0x73, 0x20, 0x6a, 0x8c,
	0xdc, 0xb8, 0x78, 0x83, 0xc0, 0xa2, 0xc1, 0x10, 0x45, 0x42, 0xa6, 0x5c, 0xcc, 0xa1, 0xc5, 0xa9,
	0x42, 0x62, 0x7a, 0x68, 0x46, 0x42, 0x54, 0x49, 0xe1, 0x10, 0x77, 0xd2, 0x3c, 0xf1, 0x48, 0x8e,
	0xf1, 0xc2, 0x23, 0x39, 0xc6, 0x07, 0x8f, 0xe4, 0x18, 0x67, 0x3c, 0x96, 0x63, 0x88, 0x12, 0x4f,
	0x4f, 0xcd, 0x03, 0xdb, 0xa1, 0x8f, 0xaa, 0x23, 0x89, 0x0d, 0x2c, 0x6a, 0x0c, 0x08, 0x00, 0x00,
	0xff, 0xff, 0x1d, 0x19, 0x08, 0x48, 0xb5, 0x00, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ResumeServiceClient is the client API for ResumeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ResumeServiceClient interface {
	Use(ctx context.Context, in *Resume, opts ...grpc.CallOption) (*Resume, error)
}

type resumeServiceClient struct {
	cc *grpc.ClientConn
}

func NewResumeServiceClient(cc *grpc.ClientConn) ResumeServiceClient {
	return &resumeServiceClient{cc}
}

func (c *resumeServiceClient) Use(ctx context.Context, in *Resume, opts ...grpc.CallOption) (*Resume, error) {
	out := new(Resume)
	err := c.cc.Invoke(ctx, "/resume_service.ResumeService/Use", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ResumeServiceServer is the server API for ResumeService service.
type ResumeServiceServer interface {
	Use(context.Context, *Resume) (*Resume, error)
}

// UnimplementedResumeServiceServer can be embedded to have forward compatible implementations.
type UnimplementedResumeServiceServer struct {
}

func (*UnimplementedResumeServiceServer) Use(ctx context.Context, req *Resume) (*Resume, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Use not implemented")
}

func RegisterResumeServiceServer(s *grpc.Server, srv ResumeServiceServer) {
	s.RegisterService(&_ResumeService_serviceDesc, srv)
}

func _ResumeService_Use_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Resume)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ResumeServiceServer).Use(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/resume_service.ResumeService/Use",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ResumeServiceServer).Use(ctx, req.(*Resume))
	}
	return interceptor(ctx, in, info, handler)
}

var _ResumeService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "resume_service.ResumeService",
	HandlerType: (*ResumeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Use",
			Handler:    _ResumeService_Use_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "resume_service.proto",
}
