// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: user_service.proto

package user_service

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

func init() { proto.RegisterFile("user_service.proto", fileDescriptor_292f630cd9eb4c90) }

var fileDescriptor_292f630cd9eb4c90 = []byte{
	// 297 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x92, 0xc1, 0x4a, 0xc3, 0x40,
	0x10, 0x86, 0x2d, 0x88, 0xc2, 0x54, 0x45, 0x06, 0xf5, 0x10, 0x34, 0x17, 0x0f, 0xde, 0x2a, 0x58,
	0x8f, 0x5e, 0xb4, 0xb5, 0xa1, 0xd8, 0x83, 0x24, 0x04, 0xc1, 0x8b, 0x44, 0x33, 0xda, 0x85, 0x6d,
	0x92, 0xee, 0x6c, 0xf4, 0x55, 0x7c, 0x0f, 0x5f, 0xc2, 0xa3, 0x8f, 0x20, 0xf1, 0x45, 0x24, 0xbb,
	0x0a, 0x5d, 0x6b, 0xa3, 0xc7, 0xfd, 0xfe, 0x7f, 0xbe, 0x6c, 0x86, 0x05, 0x2c, 0x99, 0xd4, 0x0d,
	0x93, 0x7a, 0x14, 0x77, 0xd4, 0x29, 0x54, 0xae, 0x73, 0x5c, 0x9b, 0x65, 0xde, 0xa6, 0x39, 0x4d,
	0xf2, 0x94, 0xa4, 0xcd, 0x8f, 0x5e, 0x96, 0xa1, 0x1d, 0x33, 0xa9, 0xc8, 0x36, 0xf0, 0x04, 0xa0,
	0xa7, 0x28, 0xd1, 0x54, 0x43, 0xc4, 0x8e, 0xa3, 0xac, 0x99, 0xe7, 0xcd, 0xb3, 0x2b, 0xa1, 0xc7,
	0x41, 0x3c, 0xec, 0xe3, 0x31, 0x40, 0x5c, 0xa4, 0x4d, 0xd3, 0xbf, 0x30, 0x1c, 0x00, 0xf4, 0x49,
	0xd2, 0xd7, 0x54, 0x83, 0xdf, 0xdb, 0x75, 0xb3, 0x90, 0xb8, 0xc8, 0x33, 0xa6, 0x48, 0x27, 0xba,
	0x64, 0xec, 0xc2, 0x6a, 0x40, 0xda, 0x48, 0xb6, 0xdc, 0xe2, 0x40, 0x48, 0xbd, 0xe0, 0xe3, 0x23,
	0x68, 0x07, 0xa4, 0x4f, 0xa5, 0xac, 0x4f, 0x8c, 0x7b, 0x6e, 0x65, 0x24, 0xd8, 0x08, 0x43, 0x9a,
	0x96, 0xc4, 0xda, 0xf3, 0x17, 0xc5, 0xf6, 0x22, 0xd8, 0x83, 0x76, 0x9c, 0x89, 0x69, 0x49, 0xe7,
	0x93, 0x44, 0x48, 0xdc, 0x71, 0xeb, 0x43, 0xb6, 0xe1, 0x1f, 0xff, 0x71, 0x01, 0xeb, 0x76, 0x8b,
	0x21, 0xdd, 0x2b, 0xe2, 0x31, 0xce, 0xd5, 0x0d, 0xfe, 0xbe, 0x53, 0xb3, 0x2c, 0x82, 0x0d, 0x2b,
	0xbb, 0x4c, 0x98, 0x9f, 0x72, 0x95, 0xe2, 0xfe, 0x8f, 0x2d, 0x38, 0xe9, 0xbf, 0xa4, 0x67, 0x07,
	0xaf, 0x95, 0xdf, 0x7a, 0xab, 0xfc, 0xd6, 0x7b, 0xe5, 0xb7, 0x9e, 0x3f, 0xfc, 0xa5, 0xeb, 0xed,
	0x07, 0xca, 0xcc, 0x8b, 0x3a, 0x9c, 0x9d, 0xbb, 0x5d, 0x31, 0xac, 0xfb, 0x19, 0x00, 0x00, 0xff,
	0xff, 0x30, 0xe3, 0x7b, 0x65, 0x9b, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// UserServiceClient is the client API for UserService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type UserServiceClient interface {
	CreateUser(ctx context.Context, in *User, opts ...grpc.CallOption) (*UserWithGUID, error)
	UpdateUser(ctx context.Context, in *User, opts ...grpc.CallOption) (*User, error)
	DeleteUser(ctx context.Context, in *UserWithGUID, opts ...grpc.CallOption) (*ResponseStatus, error)
	GetUser(ctx context.Context, in *Filter, opts ...grpc.CallOption) (*User, error)
	GetAllUsers(ctx context.Context, in *ListUserRequest, opts ...grpc.CallOption) (*ListUserResponse, error)
	UniqueEmail(ctx context.Context, in *IsUnique, opts ...grpc.CallOption) (*ResponseStatus, error)
	UpdateRefresh(ctx context.Context, in *RefreshRequest, opts ...grpc.CallOption) (*ResponseStatus, error)
	UpdatePassword(ctx context.Context, in *UpdatePasswordRequest, opts ...grpc.CallOption) (*ResponseStatus, error)
}

type userServiceClient struct {
	cc *grpc.ClientConn
}

func NewUserServiceClient(cc *grpc.ClientConn) UserServiceClient {
	return &userServiceClient{cc}
}

func (c *userServiceClient) CreateUser(ctx context.Context, in *User, opts ...grpc.CallOption) (*UserWithGUID, error) {
	out := new(UserWithGUID)
	err := c.cc.Invoke(ctx, "/user_service.UserService/CreateUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) UpdateUser(ctx context.Context, in *User, opts ...grpc.CallOption) (*User, error) {
	out := new(User)
	err := c.cc.Invoke(ctx, "/user_service.UserService/UpdateUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) DeleteUser(ctx context.Context, in *UserWithGUID, opts ...grpc.CallOption) (*ResponseStatus, error) {
	out := new(ResponseStatus)
	err := c.cc.Invoke(ctx, "/user_service.UserService/DeleteUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) GetUser(ctx context.Context, in *Filter, opts ...grpc.CallOption) (*User, error) {
	out := new(User)
	err := c.cc.Invoke(ctx, "/user_service.UserService/GetUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) GetAllUsers(ctx context.Context, in *ListUserRequest, opts ...grpc.CallOption) (*ListUserResponse, error) {
	out := new(ListUserResponse)
	err := c.cc.Invoke(ctx, "/user_service.UserService/GetAllUsers", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) UniqueEmail(ctx context.Context, in *IsUnique, opts ...grpc.CallOption) (*ResponseStatus, error) {
	out := new(ResponseStatus)
	err := c.cc.Invoke(ctx, "/user_service.UserService/UniqueEmail", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) UpdateRefresh(ctx context.Context, in *RefreshRequest, opts ...grpc.CallOption) (*ResponseStatus, error) {
	out := new(ResponseStatus)
	err := c.cc.Invoke(ctx, "/user_service.UserService/UpdateRefresh", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) UpdatePassword(ctx context.Context, in *UpdatePasswordRequest, opts ...grpc.CallOption) (*ResponseStatus, error) {
	out := new(ResponseStatus)
	err := c.cc.Invoke(ctx, "/user_service.UserService/UpdatePassword", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserServiceServer is the server API for UserService service.
type UserServiceServer interface {
	CreateUser(context.Context, *User) (*UserWithGUID, error)
	UpdateUser(context.Context, *User) (*User, error)
	DeleteUser(context.Context, *UserWithGUID) (*ResponseStatus, error)
	GetUser(context.Context, *Filter) (*User, error)
	GetAllUsers(context.Context, *ListUserRequest) (*ListUserResponse, error)
	UniqueEmail(context.Context, *IsUnique) (*ResponseStatus, error)
	UpdateRefresh(context.Context, *RefreshRequest) (*ResponseStatus, error)
	UpdatePassword(context.Context, *UpdatePasswordRequest) (*ResponseStatus, error)
}

// UnimplementedUserServiceServer can be embedded to have forward compatible implementations.
type UnimplementedUserServiceServer struct {
}

func (*UnimplementedUserServiceServer) CreateUser(ctx context.Context, req *User) (*UserWithGUID, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateUser not implemented")
}
func (*UnimplementedUserServiceServer) UpdateUser(ctx context.Context, req *User) (*User, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateUser not implemented")
}
func (*UnimplementedUserServiceServer) DeleteUser(ctx context.Context, req *UserWithGUID) (*ResponseStatus, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteUser not implemented")
}
func (*UnimplementedUserServiceServer) GetUser(ctx context.Context, req *Filter) (*User, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUser not implemented")
}
func (*UnimplementedUserServiceServer) GetAllUsers(ctx context.Context, req *ListUserRequest) (*ListUserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAllUsers not implemented")
}
func (*UnimplementedUserServiceServer) UniqueEmail(ctx context.Context, req *IsUnique) (*ResponseStatus, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UniqueEmail not implemented")
}
func (*UnimplementedUserServiceServer) UpdateRefresh(ctx context.Context, req *RefreshRequest) (*ResponseStatus, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateRefresh not implemented")
}
func (*UnimplementedUserServiceServer) UpdatePassword(ctx context.Context, req *UpdatePasswordRequest) (*ResponseStatus, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdatePassword not implemented")
}

func RegisterUserServiceServer(s *grpc.Server, srv UserServiceServer) {
	s.RegisterService(&_UserService_serviceDesc, srv)
}

func _UserService_CreateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(User)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).CreateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user_service.UserService/CreateUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).CreateUser(ctx, req.(*User))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_UpdateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(User)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).UpdateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user_service.UserService/UpdateUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).UpdateUser(ctx, req.(*User))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_DeleteUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserWithGUID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).DeleteUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user_service.UserService/DeleteUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).DeleteUser(ctx, req.(*UserWithGUID))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_GetUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Filter)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).GetUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user_service.UserService/GetUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).GetUser(ctx, req.(*Filter))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_GetAllUsers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).GetAllUsers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user_service.UserService/GetAllUsers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).GetAllUsers(ctx, req.(*ListUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_UniqueEmail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IsUnique)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).UniqueEmail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user_service.UserService/UniqueEmail",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).UniqueEmail(ctx, req.(*IsUnique))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_UpdateRefresh_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RefreshRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).UpdateRefresh(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user_service.UserService/UpdateRefresh",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).UpdateRefresh(ctx, req.(*RefreshRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_UpdatePassword_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdatePasswordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).UpdatePassword(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user_service.UserService/UpdatePassword",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).UpdatePassword(ctx, req.(*UpdatePasswordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _UserService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "user_service.UserService",
	HandlerType: (*UserServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateUser",
			Handler:    _UserService_CreateUser_Handler,
		},
		{
			MethodName: "UpdateUser",
			Handler:    _UserService_UpdateUser_Handler,
		},
		{
			MethodName: "DeleteUser",
			Handler:    _UserService_DeleteUser_Handler,
		},
		{
			MethodName: "GetUser",
			Handler:    _UserService_GetUser_Handler,
		},
		{
			MethodName: "GetAllUsers",
			Handler:    _UserService_GetAllUsers_Handler,
		},
		{
			MethodName: "UniqueEmail",
			Handler:    _UserService_UniqueEmail_Handler,
		},
		{
			MethodName: "UpdateRefresh",
			Handler:    _UserService_UpdateRefresh_Handler,
		},
		{
			MethodName: "UpdatePassword",
			Handler:    _UserService_UpdatePassword_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "user_service.proto",
}
