name: deploy to server

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout our repository
      uses: actions/checkout@v4

    - name: Verify Connection Details
      run: |
        echo "Connecting to host: ${{ secrets.SSH_HOST }}"
        echo "Using user: ${{ secrets.SSH_USER }}"

    - name: Deploy to Google cloud
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_KEY }}
        key_format: pem
        port: 22
        script: |
          echo "Starting deployment..."
          cd test/
          git clone git@github.com:dostonshernazarov/resume_maker.git
          sudo docker compose up -d
          echo "Deployment complete."
